name: Greenhouse Monitoring

# 매 정각마다 실행되도록 설정
on:
  schedule:
    - cron: '0 * * * *'  # 매 정각 (UTC 기준)
  workflow_dispatch:     # 수동으로 실행할 수 있는 옵션

jobs:
  greenhouse_monitoring:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
      # 레포지토리에서 코드 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v2

      # Python 설정
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python 버전 설정

      # 작업 디렉토리를 명시적으로 설정해 경로 문제 해결
      # 의존성 설치
      - name: Install dependencies
        run: |
          cd Smart-Agriculture-Programming
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Python 스크립트 실행
      - name: Run greenhouse monitoring script
        run: |
          cd Smart-Agriculture-Programming/project08
          python shading_film1.py
