name: Run Greenhouse Monitoring Code

on:
  schedule:
    - cron: '*/1 * * * *' # 매일 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        shell: cmd
        run: |
          python project08/shading_film1.py
