name: Run Python Code

on:
  schedule:
    - cron: '0 * * * *'  # 1시간 마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # 최신 버전의 Python 사용

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python project08/shading_film1.py  # 스크립트 파일 경로

      - name: Upload graph artifact
        uses: actions/upload-artifact@v2
        with:
          name: weather-data-graph
          path: weather_data_graph.png  # 그래프 이미지 파일 경로

