name: Run Python Code

on:
  schedule:
    - cron: '0 * * * *' # Executes every hour
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python project08/shading_film1.py # Replace with your actual Python file name.

      - name: Upload Graph Artifact
        uses: actions/upload-artifact@v3
        with:
          name: weather-graph
          path: C:\Users\서보성\Desktop # Replace with the actual path to your graph file

