name: Run Greenhouse Monitoring Code

on:
  schedule:
    - cron: '0 */24 * * *' # 매일 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        working-directory: Smart-Agriculture-Programming
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        working-directory: Smart-Agriculture-Programming/project08
        shell: cmd
        run: python shading_film1.py

      - name: Deploy to Cafe24 Web Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/www/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
